DROP POLICY IF EXISTS "Authenticated can manage restaurant tables" ON public.restaurant_tables;
CREATE POLICY "Restaurant access tables" ON public.restaurant_tables FOR ALL TO authenticated USING (public.can_access(auth.uid(),'restaurante')) WITH CHECK (public.can_access(auth.uid(),'restaurante'));
DROP POLICY IF EXISTS "Authenticated can manage restaurant orders" ON public.restaurant_orders;
CREATE POLICY "Restaurant access orders" ON public.restaurant_orders FOR ALL TO authenticated USING (public.can_access(auth.uid(),'restaurante')) WITH CHECK (public.can_access(auth.uid(),'restaurante'));
DROP POLICY IF EXISTS "Authenticated can manage menu items" ON public.restaurant_menu_items;
CREATE POLICY "Restaurant access menu" ON public.restaurant_menu_items FOR ALL TO authenticated USING (public.can_access(auth.uid(),'restaurante')) WITH CHECK (public.can_access(auth.uid(),'restaurante'));
DROP POLICY IF EXISTS "Authenticated can manage wash queue" ON public.wash_queue;
CREATE POLICY "Wash access queue" ON public.wash_queue FOR ALL TO authenticated USING (public.can_access(auth.uid(),'lavagem')) WITH CHECK (public.can_access(auth.uid(),'lavagem'));
DROP POLICY IF EXISTS "Authenticated can manage wash services" ON public.wash_services;
CREATE POLICY "Wash access services" ON public.wash_services FOR ALL TO authenticated USING (public.can_access(auth.uid(),'lavagem')) WITH CHECK (public.can_access(auth.uid(),'lavagem'));
DROP POLICY IF EXISTS "Authenticated can manage school contracts" ON public.school_contracts;
CREATE POLICY "Transport access contracts" ON public.school_contracts FOR ALL TO authenticated USING (public.can_access(auth.uid(),'transporte')) WITH CHECK (public.can_access(auth.uid(),'transporte'));
DROP POLICY IF EXISTS "Authenticated can manage school routes" ON public.school_routes;
CREATE POLICY "Transport access routes" ON public.school_routes FOR ALL TO authenticated USING (public.can_access(auth.uid(),'transporte')) WITH CHECK (public.can_access(auth.uid(),'transporte'));
DROP POLICY IF EXISTS "Authenticated can manage activity logs" ON public.activity_logs;
CREATE POLICY "Sector access logs" ON public.activity_logs FOR ALL TO authenticated USING (public.can_access(auth.uid(), sector)) WITH CHECK (public.can_access(auth.uid(), sector));
DROP POLICY IF EXISTS "Authenticated can manage sectors" ON public.sectors;
CREATE POLICY "Staff read sectors" ON public.sectors FOR SELECT TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'tecnico'));
CREATE POLICY "Admin manage sectors" ON public.sectors FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));